project:
  type: book
  output-dir: docs
  
execute:
  cache: true

book:
  title: "EVR-5086 Assignments"
  downloads: [pdf]
  author: "Adyan Rios"
  date: today
  chapters:
    - index.qmd
    - assignment1/assignment1.qmd

  site-url: https://arios101-fiu.github.io/EVR-5086-Assignement1/
  repo-url: https://github.com/arios101-fiu/EVR-5086-Assignement1
  repo-actions: [edit, source, issue]
  search: true
  
bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-depth: 2
  pdf:
    toc-depth: 2
    
editor: visual

