project:
  type: book
  output-dir: docs
  
execute:
  cache: true

book:
  title: "EVR-5086 Assignment 1 - Calculus Review"
  downloads: [pdf]
  author: "Adyan Rios"
  date: today
  chapters:
    - index.qmd
    - polynomial.qmd
    - tripole.qmd
  options:
    book-chapter-level: true

  site-url: https://arios101-fiu.github.io/EVR-5086-Assignement1/
  repo-url: https://github.com/arios101-fiu/EVR-5086-Assignement1
  repo-actions: [edit, source, issue]
  search: true
  
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    toc-depth: 2
    
editor: visual

